# filepath: /Users/mohammedal-olofi/Documents/flask-argocd-example/k8s/dev/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: dev
  labels:
    app: flask-app
    env: dev
spec:
  type: NodePort
  selector:
    app: flask-app
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 30002  # Choose a port in the range 30000-32767