apiVersion: v1
kind: Service
metadata:
  name: flask-app-dev
  namespace: dev
  labels:
    app: flask-app
    env: dev
spec:
  selector:
    app: flask-app
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001