# filepath: /Users/mohammedal-olofi/Documents/flask-argocd-example/k8s/prod/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-app-prod
  namespace: prod
  labels:
    app: flask-app
    env: prod
spec:
  type: NodePort
  selector:
    app: flask-app
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 30001  # Choose a port in the range 30000-32767